version: '3.9'
services:
  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "${USER_PORT}:${USER_PORT}"              # gRPC port for user service
    env_file:
      - ./user_service/.env                       # Load env specific to user service
    depends_on:
      - postgres

  message-service:
    build:
      context: ./message_service
      dockerfile: Dockerfile
    ports:
      - "${MESSAGE_PORT}:${MESSAGE_PORT}"        # gRPC port for message service
    env_file:
      - ./message_service/.env                    # Load env specific to message service
    depends_on:
      - postgres

  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"                              # HTTP port for API Gateway
    depends_on:
      - user-service
      - message-service

  postgres:
    image: postgres:14
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
